### ISSUE TITLE
Config cannot handle `null`-values

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/config#1]
`typeof null === 'object'`, therefore the `mergeDeep` will fail when it is trying to get keys of a `null`-value (https://github.com/kaliberjs/config/blob/82a4d01e8a1ec6cc4291d30f4fd5276462563cd9/index.js#L38)

**Comment by EECOLOR** [comment]
`null` should be treated as `undefined`

**Comment by EECOLOR** [comment]
Solved in v0.0.2 which apparently was not released yet.
